/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/three/person0jump/person0jump.gltf -o src/three1/person0jump.jsx -r public 
Author: joaobaltieri (https://sketchfab.com/joaobaltieri)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/square-head-character-free-demo-2b56f800db6e437b80d2f5cfcc16885c
Title: Square Head Character (Free Demo)
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Person0jump(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/three/person0jump/person0jump.gltf')
  const { actions } = useAnimations(animations, group)
  // console.log(actions);
  useEffect(()=>{
    actions["Idle"].play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={1.676}>
          <group name="9e0a180d616944c3b952d874bd3e3171fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Square_Head_Armature">
                  <group name="Object_5">
                    <primitive object={nodes._rootJoint} />
                    <group name="Object_34" />
                    <skinnedMesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.character_material_primary} skeleton={nodes.Object_35.skeleton} />
                    <skinnedMesh name="Object_36" geometry={nodes.Object_36.geometry} material={materials.character_material_secondary} skeleton={nodes.Object_36.skeleton} />
                    <skinnedMesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.character_material_tertiary} skeleton={nodes.Object_37.skeleton} />
                  </group>
                </group>
                <group name="Square_Head_Character" />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/three/person0jump/person0jump.gltf')
