/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: moxstudios (https://sketchfab.com/moxstudios)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/super-meat-boy-free-9ef65984d2404dfa9138abb982ab0971
Title: Super Meat Boy Free
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
export default function Model(props) {

  const { nodes, materials } = useGLTF('/three/meatBoy/scene.gltf');
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Super_meat} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Super_meat.001']} />
        <mesh geometry={nodes.Object_4.geometry} material={materials['Super_meat.001']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Super_meat.001']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['Super_meat.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/three/meatBoy/scene.gltf')
